
version: 1.0.{build}


image: Visual Studio 2019


environment:
  JAVA_HOME: C:\Program Files\Java\jdk11
  MAVEN_HOME: C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3
  PATH: 'C:\Program Files\Java\jdk11\bin;%MAVEN_HOME%\bin;%PATH%'


install:

  - choco install -y maven
  - choco install -y gradle


  - java -version
  - mvn --version
  - gradle --version


build_script:
  - gradle build


test_script:
  - gradle test




notifications:
  - provider: Email
    to:
      - your-email@example.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true